name: nlp-final
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - sqlite
  - pytorch::pytorch
  - pip:
    - -r requirements.txt
